apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: my-sink-connector
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: io.confluent.connect.jdbc.JdbcSinkConnector
  tasksMax: 1
  config:
    "topics": "customers"
    "connection.url": "jdbc:postgresql://postgres:5432/inventory?user=postgresuser&password=postgrespw"
    "transforms": "unwrap"
    "transforms.unwrap.type": "io.debezium.transforms.ExtractNewRecordState"
    "transforms.unwrap.drop.tombstones": "false"
    "auto.create": "true"
    "insert.mode": "upsert"
    "delete.enabled": "true"
    "pk.fields": "id"
    "pk.mode": "record_key"
